# Creación de serie temporal

```{r, include=FALSE}
#cargue del data set
folder_path <- "C:/Users/e184385/OneDrive - WFT/Desktop/Msc/Semestre 2/Analisis de series de tiempo/DJI"
file_path <- file.path(folder_path, "dow_jones_index.data")

# Leer el archivo CSV
my_data <- read.csv(file_path, header = TRUE, sep = ",")  # `sep` para indicar que es CSV

# Convertir columnas de caracteres a numéricos
numeric_columns <- c("open", "high", "low", "close", "next_weeks_open", "next_weeks_close")  # Las columnas que contienen precios

# Remover el símbolo `$` y convertir a numérico
for (col in numeric_columns) {
  my_data[[col]] <- as.numeric(gsub("\\$", "", my_data[[col]]))
}

# Obtener la primera y ultima fecha de data frame
first_date <- min(my_data$date, na.rm = TRUE)  # `na.rm = TRUE` para ignorar NA
last_date <- max(my_data$date, na.rm = TRUE)
print(first_date)  # Primera fecha
print(last_date)   # Última fecha

# Imputar valores faltantes con la media de la columna
my_data$percent_change_volume_over_last_wk[is.na(my_data$percent_change_volume_over_last_wk)] <- 
  mean(my_data$percent_change_volume_over_last_wk, na.rm = TRUE)

# Imputar valores faltantes con la mediana de la columna
my_data$previous_weeks_volume[is.na(my_data$previous_weeks_volume)] <- 
  median(my_data$previous_weeks_volume, na.rm = TRUE)

# Convertir la columna 'date' a formato Date
my_data$date <- as.Date(my_data$date, format = "%m/%d/%Y")

# ordenar por fecha
my_data <- my_data[order(my_data$date), ] 

# Crear un nuevo data frame con solo IBM
data_ibm <- subset(my_data, stock == "IBM")

```


## Determinar la frecuencia de la serie temporal

La frecuencia determina cuántas observaciones ocurren por unidad de
tiempo. Para establecer esto, necesitamos saber la distancia entre las
fechas y determinar la frecuencia.

```{r}
# Verificar la diferencia entre fechas para determinar la frecuencia
date_diff <- diff(data_ibm$date)  # Calcular la diferencia entre fechas

# Verificar la distribución de los intervalos
table(date_diff)

# Promedio de la diferencia entre fechas
mean(date_diff)  # Para ver el intervalo promedio


```

## Crear la serie temporal con frecuencia semanal

```{r}
# Crear una serie temporal a partir de 'close' y la fecha de inicio
# Frecuencia de 52 semanas por año, para datos semanales
ts_data <- ts(data_ibm$close, start = c(2011, 1), frequency = 52)

# Verificar la serie temporal
print(ts_data)

# Graficar la serie temporal
plot(ts_data, type = "l", main = "Serie Temporal del Precio de Cierre de IBM", 
     xlab = "Tiempo", ylab = "Precio de Cierre")

```

